/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Phases {
  available_units: number | null;
  created_at: Generated<Timestamp | null>;
  currently_selling: Generated<boolean | null>;
  expected_completion_date: Timestamp | null;
  id: Generated<string>;
  name: string;
  phase_number: number;
  project_id: string;
  sold_units: Generated<number | null>;
  start_date: Timestamp | null;
  status: string;
  total_units: number;
  updated_at: Generated<Timestamp | null>;
}

export interface Projects {
  affordable_housing_percentage: Numeric | null;
  affordable_housing_units: number | null;
  amenities: Json | null;
  architect: string | null;
  average_price_per_sqft: Numeric | null;
  borough: string | null;
  building_class: string | null;
  building_type: string | null;
  city: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  developer: string;
  financing_options: string[] | null;
  has_421a: Generated<boolean | null>;
  has_485x: Generated<boolean | null>;
  id: Generated<string>;
  incentives: string[] | null;
  last_price_update: Timestamp | null;
  last_synced_at: Timestamp | null;
  location: string | null;
  marketing_name: string;
  name: string;
  neighborhood: string | null;
  price_max: Numeric | null;
  price_min: Numeric | null;
  pricing_strategy: string | null;
  state: string;
  status: Generated<string>;
  street: string;
  tax_abatement_expiration: Timestamp | null;
  tax_lot_block: string | null;
  tax_lot_lot: string | null;
  timeline: Json | null;
  total_floors: number | null;
  total_units: number | null;
  units_available: number | null;
  units_sold: number | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  website: string | null;
  year_built: number | null;
  zip_code: string;
  zoning: string | null;
}

export interface Units {
  appliances: string[] | null;
  bathrooms: Numeric | null;
  bedrooms: Numeric | null;
  created_at: Generated<Timestamp | null>;
  exposure: string | null;
  features: Json | null;
  floor: number | null;
  flooring: string | null;
  id: Generated<string>;
  layout_line: string | null;
  original_price: Numeric | null;
  outdoor_space_sqft: number | null;
  phase_id: string | null;
  price: Numeric;
  price_per_sqft: Generated<Numeric | null>;
  project_id: string;
  sqft: number;
  status: Generated<string>;
  unit_number: string;
  unit_type: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  phases: Phases;
  projects: Projects;
  units: Units;
}
